Fix: postRender automatically setting blank component as completed
adaptlearning/adapt-contrib-blank pull request #46
Opened 2022-11-16 13:17 UTC by cahirodoherty-learningpool

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #45 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* postRender automatically setting blank component as completed on page view

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Create a course with blank components and page level progress
2. PLP should fill immediately on page load
3. Clicking PLP will show blank components individually have completed

2022-11-16 14:05 UTC, paulstevendev commented
Our requirements are that the blank component behaves according to the "Is this optional" setting. We use this component to determine if a user has viewed a page by placing a blank component at the top of each page with all other components set to optional. Therefore if you place a blank component at the top of the page and set it to NOT optional I would expect the menu of the course not to detect the page as complete until the user opens the page. This is how it currently works with the open source blank component but the Learning Pool one appears to act as optional despite the setting that has been set for "Is this optional"

2022-12-06 10:57 UTC, cahirodoherty-learningpool commented
Yes this is part of the difference that you are seeing @paulstevendev. The LearningPool AT will override these components and set them as optional always. We want to remove this when the new component functionality is added.
The changes to the blank component would effectively make page completion occur upon opening when a blank component is on that page and is the only non-optional component. Does that make sense?

2022-12-06 11:23 UTC, paulstevendev commented
@cahirodoherty-learningpool - the suggestion @oliverfoster has made sounds like a good compromise. If you did have a page where all the non blank components are set to optional then adding any blank components with a default setting of optional would result in page completion occur upon opening the course. However forcing the blank component to always act as optional is not an ideal solution for us so hopefully you can go with the suggestion by @oliverfoster

2022-12-06 11:47 UTC, cahirodoherty-learningpool commented
Yeah that works for us. I've just pushed another commit

2022-12-06 11:52 UTC, paulstevendev commented
Thanks Cahir

2023-01-03 16:41 UTC, chris-steele approved these changes
This makes eminent sense

2023-01-09 11:38 UTC, oliverfoster requested changes

2023-01-09 11:38 UTC, oliverfoster commented on properties.schema
> +      "default": false
```suggestion
      "default": true
```

2023-01-09 11:38 UTC, oliverfoster commented on js/blankView.js
> +    this.setCompletionStatus();
```suggestion
    this.setupInviewCompletion();
```

2023-01-09 11:39 UTC, oliverfoster commented on js/blankView.js
> +    this.setCompletionStatus();
Can we leave this as it was, as the `_isOptional: false` + inview can be useful to auto complete on page end?

2023-01-16 10:55 UTC, oliverfoster commented
Taking @paulstevendev as implicit +1

2023-01-16 10:55 UTC, merged

2023-01-24 09:50 UTC, paulstevendev commented
It doesn't appear that there are any properties appearing in the AT now for the blank component so it is impossible to set this to NOT optional.

2023-01-24 10:38 UTC, cahirodoherty-learningpool commented
> It doesn't appear that there are any properties appearing in the AT now for the blank component so it is impossible to set this to NOT optional.
> 
> Testing: info [24 Jan 23 09:56:13 +00:00] Adapt authoring tool 0.11.1. info [24 Jan 23 09:56:13 +00:00] Adapt framework 5.24.8.
> 
> Blank component: 4.1.4
> 
> ![image](https://user-images.githubusercontent.com/114067294/214264582-71abcf11-a80b-43ac-bdc5-9ff56d20e2c3.png)

Issue to resolve this raised here: https://github.com/adaptlearning/adapt-contrib-blank/issues/51